### PR TITLE
Version update

### PR DESCRIPTION
**Pull request by colleenbprice**
Merge in master and update version

### CODE REVIEW

**Comment by colleenbprice** [comment]
I don't have write access to this repository, so after you merge this, could you create a tag for built to point to?

**Comment by danrasband** [comment]
Will we merge this branch into master afterwards?

**Comment by colleenbprice** [comment]
It looked like you were using this branch for versions and the tag 3.0.0 was on this branch, so I assumed that was how you wanted to keep it.  If you want to update the version on master, I am fine with that.

**Comment by danrasband** [comment]
Let's move to master. I tried creating a pull request for version_update into master, but there were merge conflicts. If master is up-to-date, let's just bump the version there, then tag master with the appropriate version tag. I'll see if I can grant you write permissions to this repo.

**Comment by danrasband** [comment]
You should have write access now.

**Pull request closed without merging**
