### PR TITLE
Version update

### PR DESCRIPTION
**Pull request by colleenbprice**
I decided to pull in the rest of the changes from master on waynerobison/xeroizer. I also updated the version to 3.0.1.  There has been a bit of development lately over there and they did merge in my PR finally.  Maybe we should try to get them to pull the payroll branch in and just use their gem?

### CODE REVIEW

**Comment by danrasband** [comment]
Have you tested things on this branch and found that everything works as expected?

**Comment by danrasband** [comment]
I just tried to run all the tests, and I got a bunch of failures. I think we should at least try to get them all passing.

**Comment by colleenbprice** [comment]
I actually don't know how to run the tests. Where do you put the env variables that are required (consumer_key, secret, key_file)?

**Comment by colleenbprice** [comment]
NM, I figured it out.

**Pull request closed without merging**
